service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000.0
    targetPort: 3000.0
  label: backend-service-s4jsqo9unq-v5dv4t5tna
  name: backend-service-s4jsqo9unq-v5dv4t5tna
  selector: backend-service-s4jsqo9unq-v5dv4t5tna
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-backend-service-s4jsqo9unq-v5dv4t5tna
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-s4jsqo9unq-v5dv4t5tna
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: backend-service-s4jsqo9unq-v5dv4t5tna
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: backend-service-s4jsqo9unq-v5dv4t5tna
    port: 3000.0
  volume:
    name: pvc-backend-service-s4jsqo9unq-v5dv4t5tna
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    mariadb:
      name: secret-database-s4jsqo9unq-04nlmg4ro3

  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-s4jsqo9unq-v5dv4t5tna
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
