service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000.0
    targetPort: 3000.0
  label: backend-service-s4jsqo9unq-v5dv4t5tna
  name: backend-service-s4jsqo9unq-v5dv4t5tna
  selector: backend-service-s4jsqo9unq-v5dv4t5tna
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-backend-service-s4jsqo9unq-v5dv4t5tna
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-s4jsqo9unq-v5dv4t5tna
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: backend-service-s4jsqo9unq-v5dv4t5tna
    tag: "7509-4231-backend-service-s4jsqo9unq-v5dv4t5tna-3791e5e"
    secret: regsecret
  container:
    name: backend-service-s4jsqo9unq-v5dv4t5tna
    port: 3000.0
  volume:
    name: pvc-backend-service-s4jsqo9unq-v5dv4t5tna
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
    mariadb:
      name: secret-database-s4jsqo9unq-04nlmg4ro3

  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-s4jsqo9unq-v5dv4t5tna
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
