service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: config-pctigguli9
  name: config-pctigguli9
  selector: config-pctigguli9
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-config-pctigguli9
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: config-pctigguli9
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: config-pctigguli9
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: config-pctigguli9
    port: 8080
  volume:
    name: pvc-config-pctigguli9
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    rabbitmq:
      name: rabbitmq-service-1-hiuj1eg7hk-secret
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-config-pctigguli9
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
