service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: config-pctigguli9
  name: config-pctigguli9
  selector: config-pctigguli9
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-config-pctigguli9
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: config-pctigguli9
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: config-pctigguli9
    tag: "7509-4231-config-pctigguli9-a5824ce"
    secret: regsecret
  container:
    name: config-pctigguli9
    port: 8080
  volume:
    name: pvc-config-pctigguli9
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
    rabbitmq:
      name: rabbitmq-service-1-hiuj1eg7hk-secret
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-config-pctigguli9
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
