apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.app.name }}
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.update.type }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app.name }}
        type: {{ .Values.deployment.app.type }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.repo.url }}:{{ .Values.deployment.image.tag }}
          ports:
              - containerPort: {{ default "8000" .Values.deployment.container.port }}
          readinessProbe:
            tcpSocket:
              port: {{ default "8000" .Values.deployment.container.port }}
          resources:
            requests:
              memory: "{{ default "64Mi" .Values.deployment.resource.request.memory }}"
              cpu: "{{ default "100m" .Values.deployment.resource.request.cpu }}"
            {{- if and (ne .Values.deployment.resource.limits.memory "0Mi") (ne .Values.deployment.resource.limits.memory "0Gi") }}
            limits:
              memory: "{{ default "64Mi" .Values.deployment.resource.limits.memory }}"
              cpu: "{{ default "100m" .Values.deployment.resource.limits.cpu }}"
            {{- end }}
          env:
            - name: SERVICE_API
              value: /{{ .Values.namespace }}/dis
            - name: SERVICE_PATH
              value: /{{ .Values.namespace }}/portal

          envFrom:
          volumeMounts:
            - name: {{ .Values.deployment.volume.name }}
              mountPath: /{{ .Values.deployment.app.name }}/logs

      volumes:
        - name: config-{{ .Values.deployment.app.name }}
          configMap:
            name: frontend-config-{{ .Values.deployment.app.name }}
        - name: {{ .Values.deployment.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}

      imagePullSecrets:
          - name: {{ .Values.deployment.image.secret }}