service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000.0
    targetPort: 3000.0
  label: backend-service-vttbierzoq-sifsp0sz4d
  name: backend-service-vttbierzoq-sifsp0sz4d
  selector: backend-service-vttbierzoq-sifsp0sz4d
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-backend-service-vttbierzoq-sifsp0sz4d
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-vttbierzoq-sifsp0sz4d
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: backend-service-vttbierzoq-sifsp0sz4d
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: backend-service-vttbierzoq-sifsp0sz4d
    port: 3000.0
  volume:
    name: pvc-backend-service-vttbierzoq-sifsp0sz4d
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    mariadb:
      name: secret-database-vttbierzoq-rh3qwmh3xr

  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-vttbierzoq-sifsp0sz4d
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
