mariadb:
  configmap:
    name: config-database-axiocsr7tw-lmfp2bx7mk
  secret:
    name: secret-database-axiocsr7tw-lmfp2bx7mk
    username: test
    password: "ROot1234!"
    root_password: "Root1234!"
    database: test
    dbhost: database-axiocsr7tw-lmfp2bx7mk
    port: 3306.0
  statefulset:
    name: database-axiocsr7tw-lmfp2bx7mk
    image:
      url: registry.turacocloud.com/turaco-common/mariadb:10.4.11
service:
  port:
    name: http
    l4_protocol: TCP
    port: 3306.0
    targetPort: 3306.0
  label: database-axiocsr7tw-lmfp2bx7mk
  name: database-axiocsr7tw-lmfp2bx7mk
  selector: database-axiocsr7tw-lmfp2bx7mk
  type:
  - ClusterIP
  - NodePort
statefulset:
  name: database-axiocsr7tw-lmfp2bx7mk
  spec:
    name: database-axiocsr7tw-lmfp2bx7mk
    servicename: database-axiocsr7tw-lmfp2bx7mk
  replicas: -@replicas@-
  container:
    name: database-axiocsr7tw-lmfp2bx7mk
    port: 3306.0
  volume:
    name: pvc-database-axiocsr7tw-lmfp2bx7mk
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  hpa:
    name: hpa-database-axiocsr7tw-lmfp2bx7mk
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
namespace: -@namespace@-
secret:
  name: 
  registry:
    name: regsecret
    url: -@imageRepoName@-
    username: -@accessKey@-
    password: -@secretKey@-
    email: info@twolinecode.com
pvc:
  name: pvc-database-axiocsr7tw-lmfp2bx7mk
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
