mariadb:
  configmap:
    name: config-database-axiocsr7tw-lmfp2bx7mk
  secret:
    name: secret-database-axiocsr7tw-lmfp2bx7mk
    username: test
    password: "ROot1234!"
    root_password: "Root1234!"
    database: test
    dbhost: database-axiocsr7tw-lmfp2bx7mk
    port: 3306.0
  statefulset:
    name: database-axiocsr7tw-lmfp2bx7mk
    image:
      url: registry.turacocloud.com/turaco-common/mariadb:10.4.11
service:
  port:
    name: http
    l4_protocol: TCP
    port: 3306.0
    targetPort: 3306.0
  label: database-axiocsr7tw-lmfp2bx7mk
  name: database-axiocsr7tw-lmfp2bx7mk
  selector: database-axiocsr7tw-lmfp2bx7mk
  type:
  - ClusterIP
  - NodePort
statefulset:
  name: database-axiocsr7tw-lmfp2bx7mk
  spec:
    name: database-axiocsr7tw-lmfp2bx7mk
    servicename: database-axiocsr7tw-lmfp2bx7mk
  replicas: 1
  container:
    name: database-axiocsr7tw-lmfp2bx7mk
    port: 3306.0
  volume:
    name: pvc-database-axiocsr7tw-lmfp2bx7mk
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  hpa:
    name: hpa-database-axiocsr7tw-lmfp2bx7mk
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
namespace: testgov2-dev
secret:
  name: 
  registry:
    name: regsecret
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
    username: robot$turaco_common
    password: Zv7beYWhgCQSOUoxZQK1RGWHdvAMltXx
    email: info@twolinecode.com
pvc:
  name: pvc-database-axiocsr7tw-lmfp2bx7mk
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
