namespace: -@namespace@-
rabbitmq:
  name: rabbitmq-service-1-hiuj1eg7hk
  username: test
  password: "Root1234!"
  port: 5672
  targetPort: 5672
  host: 
  virtualHost: /
  storageClass: tlc-block-sc
  accessMode: ReadWriteOnce
  size: 5Gi
  statefulset:
    replicas: -@replicas@-
    hpa:
      name: hpa-rabbitmq-service-1-hiuj1eg7hk
      minReplicas: -@minReplicas@-
      maxReplicas: -@maxReplicas@-
      cpu: -@cpuAutoScale@-
      memory: -@memAutoScale@-
    resource:
      request:
        memory: -@requestMemory@-
        cpu: -@requestCpu@-
      limits:
        memory: -@limitsMemory@-
        cpu: -@limitsCpu@-
