namespace: testgov2-dev
rabbitmq:
  name: rabbitmq-service-1-hiuj1eg7hk
  username: test
  password: "Root1234!"
  port: 5672
  targetPort: 5672
  host: 
  virtualHost: /
  storageClass: tlc-block-sc
  accessMode: ReadWriteOnce
  size: 5Gi
  statefulset:
    replicas: 1
    hpa:
      name: hpa-rabbitmq-service-1-hiuj1eg7hk
      minReplicas: 1
      maxReplicas: 1
      cpu: 70
      memory: -@memAutoScale@-
    resource:
      request:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 0Gi
        cpu: 0
