service:
  port:
    name: http
    l4_protocol: TCP
    port: 8761
    targetPort: 8761
  label: egov-springcloud-discovery-1-1hvv0frlg5
  name: egov-springcloud-discovery-1-1hvv0frlg5
  selector: egov-springcloud-discovery-1-1hvv0frlg5
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-egov-springcloud-discovery-1-1hvv0frlg5
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: egov-springcloud-discovery-1-1hvv0frlg5
    type: egov-springcloud-discovery
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: egov-springcloud-discovery-1-1hvv0frlg5
    tag: lastest
    secret: regsecret
  container:
    name: egov-springcloud-discovery-1-1hvv0frlg5
    port: 8761
  volume:
    name: pvc-egov-springcloud-discovery-1-1hvv0frlg5
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-egov-springcloud-discovery-1-1hvv0frlg5
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
