service:
  port:
    name: http
    l4_protocol: TCP
    port: 8761
    targetPort: 8761
  label: egov-springcloud-discovery-1-1hvv0frlg5
  name: egov-springcloud-discovery-1-1hvv0frlg5
  selector: egov-springcloud-discovery-1-1hvv0frlg5
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-egov-springcloud-discovery-1-1hvv0frlg5
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: egov-springcloud-discovery-1-1hvv0frlg5
    type: egov-springcloud-discovery
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: egov-springcloud-discovery-1-1hvv0frlg5
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: egov-springcloud-discovery-1-1hvv0frlg5
    port: 8761
  volume:
    name: pvc-egov-springcloud-discovery-1-1hvv0frlg5
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-egov-springcloud-discovery-1-1hvv0frlg5
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
