service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000.0
    targetPort: 3000.0
  label: backend-service-vttbierzoq-sifsp0sz4d
  name: backend-service-vttbierzoq-sifsp0sz4d
  selector: backend-service-vttbierzoq-sifsp0sz4d
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-backend-service-vttbierzoq-sifsp0sz4d
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-vttbierzoq-sifsp0sz4d
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: backend-service-vttbierzoq-sifsp0sz4d
    tag: "7509-4231-backend-service-vttbierzoq-sifsp0sz4d-7564612"
    secret: regsecret
  container:
    name: backend-service-vttbierzoq-sifsp0sz4d
    port: 3000.0
  volume:
    name: pvc-backend-service-vttbierzoq-sifsp0sz4d
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
    mariadb:
      name: secret-database-vttbierzoq-rh3qwmh3xr

  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-vttbierzoq-sifsp0sz4d
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
