service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000
    targetPort: 3000
  label: egov-admin-service-xk7zm5fid0
  name: egov-admin-service-xk7zm5fid0
  selector: egov-admin-service-xk7zm5fid0
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-egov-admin-service-xk7zm5fid0
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: egov-admin-service-xk7zm5fid0
    type: react
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: egov-admin-service-xk7zm5fid0
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: egov-admin-service-xk7zm5fid0
    port: 3000
  volume:
    name: pvc-egov-admin-service-xk7zm5fid0
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-egov-admin-service-xk7zm5fid0
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
