service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000
    targetPort: 3000
  label: egov-admin-service-xk7zm5fid0
  name: egov-admin-service-xk7zm5fid0
  selector: egov-admin-service-xk7zm5fid0
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-egov-admin-service-xk7zm5fid0
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: egov-admin-service-xk7zm5fid0
    type: react
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: egov-admin-service-xk7zm5fid0
    tag: "7509-4231-egov-admin-service-xk7zm5fid0-8a7fe8f"
    secret: regsecret
  container:
    name: egov-admin-service-xk7zm5fid0
    port: 3000
  volume:
    name: pvc-egov-admin-service-xk7zm5fid0
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-egov-admin-service-xk7zm5fid0
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
