service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000
    targetPort: 3000
  label: egov-portal-service-iqglnceiqe
  name: egov-portal-service-iqglnceiqe
  selector: egov-portal-service-iqglnceiqe
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-egov-portal-service-iqglnceiqe
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: egov-portal-service-iqglnceiqe
    type: react
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: egov-portal-service-iqglnceiqe
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: egov-portal-service-iqglnceiqe
    port: 3000
  volume:
    name: pvc-egov-portal-service-iqglnceiqe
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-egov-portal-service-iqglnceiqe
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
