service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000
    targetPort: 3000
  label: egov-portal-service-iqglnceiqe
  name: egov-portal-service-iqglnceiqe
  selector: egov-portal-service-iqglnceiqe
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-egov-portal-service-iqglnceiqe
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: egov-portal-service-iqglnceiqe
    type: react
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: egov-portal-service-iqglnceiqe
    tag: "7509-4231-egov-portal-service-iqglnceiqe-e329441"
    secret: regsecret
  container:
    name: egov-portal-service-iqglnceiqe
    port: 3000
  volume:
    name: pvc-egov-portal-service-iqglnceiqe
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-egov-portal-service-iqglnceiqe
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
