service:
  port:
    name: http
    l4_protocol: TCP
    port: 3000.0
    targetPort: 3000.0
  label: backend-service-axiocsr7tw-ilhzi47ydg
  name: backend-service-axiocsr7tw-ilhzi47ydg
  selector: backend-service-axiocsr7tw-ilhzi47ydg
  type:
  - ClusterIP
  - NodePort
namespace: testgov2-dev
pvc:
  name: pvc-backend-service-axiocsr7tw-ilhzi47ydg
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-axiocsr7tw-ilhzi47ydg
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: backend-service-axiocsr7tw-ilhzi47ydg
    tag: lastest
    secret: regsecret
  container:
    name: backend-service-axiocsr7tw-ilhzi47ydg
    port: 3000.0
  volume:
    name: pvc-backend-service-axiocsr7tw-ilhzi47ydg
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
    mariadb:
      name: secret-database-axiocsr7tw-lmfp2bx7mk

  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-axiocsr7tw-ilhzi47ydg
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
